// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Queue, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer, VectorIndex,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AGENT_MEMORY: SmartMemory;
  AI: Ai;
  ANALYSIS_QUEUE: Queue<import('../insight-generator').Body>;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  AUDIO_STORAGE: SmartBucket;
  DOCUMENT_EMBEDDINGS: VectorIndex;
  DOCUMENT_PROCESSOR: ServiceStub<import('../document-processor/index.js').default>;
  DOCUMENT_STORAGE: SmartBucket;
  GRAPH_DATABASE: SmartSql;
  INTELLIGENCE_PIPELINE: ServiceStub<import('../intelligence-pipeline/index.js').default>;
  logger: Logger;
  mem: KvCache;
  MEMORY_CORE: ServiceStub<import('../memory-core/index.js').default>;
  MEMORY_EMBEDDINGS: VectorIndex;
  PATTERN_DETECTOR: ServiceStub<import('../pattern-detector/index.js').default>;
  PROCESSING_QUEUE: Queue<import('../batch-processor').Body>;
  QUERY_CACHE: KvCache;
  SEARCH_ENGINE: ServiceStub<import('../search-engine/index.js').default>;
  SESSION_CACHE: KvCache;
  tracer: Tracer;
  VOICE_PROCESSOR: ServiceStub<import('../voice-processor/index.js').default>;
}
