// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, JWTVerifyResult, KvCache, Logger, MRNObject, ServiceStub, SmartMemory, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AGENT_MEMORY: SmartMemory;
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  HANSEI_INTELLIGENCE_PROCESSOR: ServiceStub<import('../hansei-intelligence-processor/index.js').default>;
  jwt?: JWTVerifyResult;
  LM_AUTH_ALLOWED_ISSUERS: string;
  LM_AUTH_ALLOWED_ORIGINS: string;
  LM_PROVIDER_WORKOS_API_KEY?: string;
  LM_PROVIDER_WORKOS_CLIENT_ID?: string;
  LM_PROVIDER_WORKOS_ORG_ID?: string;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
}
